UPDATE products SET name = 'Whisky Jack Daniel N°7 1 Lt con dosificador' WHERE id = 1;
UPDATE products SET name = 'Whisky Jack Daniel Manzana 1 Lt con dosificador' WHERE id = 2;
UPDATE products SET name = 'Whisky Jack Daniel Honey 1 Lt' WHERE id = 3;
UPDATE products SET name = 'Whisky Jack Daniel Fire 1 Lt' WHERE id = 4;
UPDATE products SET name = 'Whisky Black Label 1 Lt' WHERE id = 5;
UPDATE products SET name = 'Whisky Red Label 1 Lt' WHERE id = 6;
UPDATE products SET name = 'Ballantine Finest 1 Lt' WHERE id = 7;
UPDATE products SET name = 'Chivas Regal 12 años 1 Lt' WHERE id = 8;
UPDATE products SET name = 'Whisky Old Par 1 Lt' WHERE id = 9;
UPDATE products SET name = 'Whisky Royal Circle 1 Lt' WHERE id = 10;
UPDATE products SET name = 'Whisky Royal Circle Honey 1 Lt' WHERE id = 11;
UPDATE products SET name = 'Ron Havana Club añejo Especial 1 Lt' WHERE id = 14;
UPDATE products SET name = 'Havana Club Reserva 1 Lt' WHERE id = 15;
UPDATE products SET name = 'Havana Club 3 años 1 Lt' WHERE id = 17;
UPDATE products SET name = 'Ron Abuelo añejo 1 Lt' WHERE id = 20;
UPDATE products SET name = 'Flor de Caña 4 años 1 Lt' WHERE id = 25;
UPDATE products SET name = 'Flor de Caña 7 años 1 Lt' WHERE id = 26;
UPDATE products SET name = 'Ron Barcelo añejo 1 Lt' WHERE id = 27;
UPDATE products SET name = 'Ron Barcelo blanco 1 Lt' WHERE id = 28;
UPDATE products SET name = 'Licor Jagermeister 1 Lt 35°Alc' WHERE id = 35;
UPDATE products SET name = 'Aguardiente Blanco del Valle 1 Lt' WHERE id = 37;
UPDATE products SET name = 'Tequila Dona camila c/g 1 Lt' WHERE id = 38;
UPDATE products SET name = 'Tequila Dona camila s/g 1 Lt' WHERE id = 39;
UPDATE products SET name = 'Vodka Absolut Clásico 1 Lt' WHERE id = 44;